#!/usr/bin/env sh

cd `dirname $0`

args=""
separator=""

for arg in "$@"; do
  args+="${separator}\"$arg\""
  separator=" "
done

args="${args%"${args##*[![:space:]]}"}"

if [ -n "$args" ]
then
  ./gradlew -q run --args="$args"
else
  ./gradlew -q run
fi
